### ISSUE TITLE
CSS help

### ISSUE THREAD

**Issue by rsoloff** [rsoloff/Black-Jack#1]
@jasonseminara @amcooper @zhenpanda @WilliamfShaw 

https://github.com/rsoloff/Black-Jack

I am having a lot of trouble with my CSS. The images do not line up and I can't move my text. I want to position my text in certain spots and I want the cards to appear in a certain place when revealed. I can make the images appear and each one be a set distance to the side of it but they never line up vertically.

**Comment by WilliamfShaw** [comment]
What have you tried? Can you send us a screen shot of what this looks like as of current?
